<h2 style="margin: 24px 0 16px; font-size: 20px; font-weight: 600; font-family: 'Segoe UI', Roboto, sans-serif; color: #111827; border-bottom: 2px solid #e5e7eb; padding-bottom: 6px;">📘 Kontrola kvality dát a spracovanie chýb</h2>
<p style="font-family: 'Segoe UI', Roboto, sans-serif; color: #1f2937; line-height: 1.65; margin: 8px 0 12px;">
V tejto úlohe budete pracovať so súborom
<span style="background-color: #e5e7eb; color: #111827; font-family: monospace; padding: 2px 5px; border-radius: 4px;">sales_data_dirty.csv</span>, ktorý zámerne obsahuje problémy
typické pre dáta získané z externého zdroja.
</p>
<p style="font-family: 'Segoe UI', Roboto, sans-serif; color: #1f2937; line-height: 1.65; margin: 8px 0 12px;">
Vašou úlohou nebude iba „opraviť CSV“, ale navrhnúť postup, ktorý by bolo možné
neskôr použiť ako súčasť dátovej pipeline. Pri každom kroku preto odlišujte
<strong>detekciu problému</strong>, <strong>rozhodnutie o jeho spracovaní</strong>
a <strong>kontrolu výsledku</strong>.
</p>
<p style="font-family: 'Segoe UI', Roboto, sans-serif; color: #1f2937; line-height: 1.65; margin: 8px 0 12px;">V datasete sa môžu nachádzať napríklad:</p>
<ul style="font-family: 'Segoe UI', Roboto, sans-serif; color: #1f2937; line-height: 1.7; margin-top: 6px;">
  <li>chýbajúce hodnoty,</li>
  <li>nekonzistentné kategórie,</li>
  <li>nesprávne dátové typy,</li>
  <li>neplatné alebo podozrivé číselné hodnoty,</li>
  <li>duplicitné identifikátory objednávok,</li>
  <li>rôzne formáty dátumov a neplatné dátumy,</li>
  <li>nekonzistentné telefónne čísla.</li>
</ul>
<div
  style="margin-top: 12px; background-color: #fff7ed; border-left: 4px solid #f59e0b; padding: 12px; border-radius: 4px;">
⚠️ <strong>Nezabudnite:</strong> Pri validácii dát neplatí, že každú chybu je správne
automaticky nahradiť nulou. Ak hodnotu nevieme spoľahlivo opraviť, je často lepšie
ju označiť ako neplatnú alebo záznam oddeliť na ďalšiu kontrolu.
</div>

<p style="font-family: 'Segoe UI', Roboto, sans-serif; color: #1f2937; line-height: 1.65; margin: 8px 0 12px;">Pri riešení pracujte s nasledujúcimi pravidlami:</p>
<ul style="font-family: 'Segoe UI', Roboto, sans-serif; color: #1f2937; line-height: 1.7; margin-top: 6px;">
  <li><span style="background-color: #e5e7eb; color: #111827; font-family: monospace; padding: 2px 5px; border-radius: 4px;">OrderID</span> musí existovať, mať formát <span style="background-color: #e5e7eb; color: #111827; font-family: monospace; padding: 2px 5px; border-radius: 4px;">ORDdddd</span> a byť unikátny.</li>
  <li><span style="background-color: #e5e7eb; color: #111827; font-family: monospace; padding: 2px 5px; border-radius: 4px;">Region</span> musí po zjednotení obsahovať iba North, South, East alebo West.</li>
  <li><span style="background-color: #e5e7eb; color: #111827; font-family: monospace; padding: 2px 5px; border-radius: 4px;">Product</span> musí patriť do povolenej množiny produktov.</li>
  <li><span style="background-color: #e5e7eb; color: #111827; font-family: monospace; padding: 2px 5px; border-radius: 4px;">Quantity</span> musí byť kladné celé číslo.</li>
  <li><span style="background-color: #e5e7eb; color: #111827; font-family: monospace; padding: 2px 5px; border-radius: 4px;">SalesAmount</span> musí byť kladná číselná hodnota.</li>
  <li><span style="background-color: #e5e7eb; color: #111827; font-family: monospace; padding: 2px 5px; border-radius: 4px;">Discount</span> musí byť číslo v intervale 0 až 100.</li>
  <li><span style="background-color: #e5e7eb; color: #111827; font-family: monospace; padding: 2px 5px; border-radius: 4px;">OrderDate</span> a <span style="background-color: #e5e7eb; color: #111827; font-family: monospace; padding: 2px 5px; border-radius: 4px;">DeliveryDate</span> musia byť platné dátumy a dodanie nesmie byť pred objednávkou.</li>
  <li><span style="background-color: #e5e7eb; color: #111827; font-family: monospace; padding: 2px 5px; border-radius: 4px;">PhoneNumber</span> je nepovinný, ale ak je vyplnený, po odstránení formátovacích znakov musí obsahovať 10 až 15 číslic.</li>
</ul>

<h2 style="margin: 24px 0 16px; font-size: 20px; font-weight: 600; font-family: 'Segoe UI', Roboto, sans-serif; color: #111827; border-bottom: 2px solid #e5e7eb; padding-bottom: 6px;">💻 Úloha 1 – Bezpečné načítanie vstupného súboru</h2>
<p style="font-family: 'Segoe UI', Roboto, sans-serif; color: #1f2937; line-height: 1.65; margin: 8px 0 12px;">Načítajte <span style="background-color: #e5e7eb; color: #111827; font-family: monospace; padding: 2px 5px; border-radius: 4px;">sales_data_dirty.csv</span> tak, aby program vedel zrozumiteľne reagovať aj v prípade, že súbor neexistuje, je prázdny alebo sa ho nepodarí korektne parsovať.</p>
<ul style="font-family: 'Segoe UI', Roboto, sans-serif; color: #1f2937; line-height: 1.7; margin-top: 6px;">
<li>použite <span style="background-color: #e5e7eb; color: #111827; font-family: monospace; padding: 2px 5px; border-radius: 4px;">try/except</span>,</li>
<li>po úspešnom načítaní vypíšte počet riadkov a stĺpcov, zobrazte prvých 5 riadkov.</li>
</ul>
<div
  style="margin-top: 12px; background-color: #f9fafb; border-left: 4px solid #60a5fa; padding: 12px; border-radius: 4px;">
  💡 <strong>Pomôcka:</strong> Pri čítaní súboru sa môže stať, že súbor neexistuje,
je prázdny alebo má poškodenú štruktúru. Takéto situácie je vhodné zachytiť pomocou
<span style="background-color: #e5e7eb; color: #111827; font-family: monospace; padding: 2px 5px; border-radius: 4px;">try/except</span>.
<br><br>
Príklad princípu:
<pre style="background: #f9fafb; padding: 14px; border-radius: 8px; overflow: auto; font-size: 14px; line-height: 1.5; font-family: ui-monospace, SFMono-Regular, Menlo, monospace; margin: 10px 0 14px;">try:
    # operácia, ktorá môže zlyhať
except SomeError:
    # reakcia na konkrétny typ chyby</pre>
Pri CSV sa môžete stretnúť napríklad s <span style="background-color: #e5e7eb; color: #111827; font-family: monospace; padding: 2px 5px; border-radius: 4px;">FileNotFoundError</span>,
<span style="background-color: #e5e7eb; color: #111827; font-family: monospace; padding: 2px 5px; border-radius: 4px;">EmptyDataError</span> alebo <span style="background-color: #e5e7eb; color: #111827; font-family: monospace; padding: 2px 5px; border-radius: 4px;">ParserError</span>.
Vašou úlohou je vybrať vhodné výnimky a zobraziť zmysluplnú informáciu o tom, čo zlyhalo.
</div>

In [1]:
from pathlib import Path
import pandas as pd
import numpy as np

base_dir = Path.cwd()
if not (base_dir / "sales_data_dirty.csv").exists():
    base_dir = base_dir / "week_5" / "zadanie_5b"
input_path = base_dir / "sales_data_dirty.csv"
try:
    df = pd.read_csv(input_path, dtype="string")
    if df.empty:
        raise pd.errors.EmptyDataError("Súbor neobsahuje žiadne záznamy.")
except FileNotFoundError as error:
    raise FileNotFoundError(f"Súbor sa nenašiel: {input_path}") from error
except pd.errors.EmptyDataError as error:
    raise ValueError("Vstupný súbor je prázdny.") from error
except (pd.errors.ParserError, UnicodeDecodeError) as error:
    raise ValueError(f"CSV sa nepodarilo načítať: {error}") from error
print("Počet riadkov a stĺpcov:", df.shape)
display(df.head())

Počet riadkov a stĺpcov: (200, 10)

,OrderID,CustomerName,Region,Product,Quantity,SalesAmount,Discount,OrderDate,DeliveryDate,PhoneNumber
0,ORD1095,Bob Smith,South,Unknown,-1,2710.16,15,2025-04-06,2024-02-30,+2348012345678
1,ORD1015,Charlie Lee,West,phone,7,840USD,20,2025-01-16,2025-01-19,12345
2,ORD1030,Alice Johnson,West,phone,6,1805.15,15,2025-01-31,2025-02-01,555-018X
3,ORD1158,Ibrahim Musa,North,phone,0,<NA>,5,2025-06-08,2025-06-21,+1-202-555-0178
4,ORD1128,Bob Smith,SOUTH,Laptop,9,3083.23,5,2025-05-09,2025-05-11,<NA>

<h2 style="margin: 24px 0 16px; font-size: 20px; font-weight: 600; font-family: 'Segoe UI', Roboto, sans-serif; color: #111827; border-bottom: 2px solid #e5e7eb; padding-bottom: 6px;">💻 Úloha 2 – Základný audit datasetu</h2>
<p style="font-family: 'Segoe UI', Roboto, sans-serif; color: #1f2937; line-height: 1.65; margin: 8px 0 12px;">Skôr než začnete hodnoty opravovať, vytvorte si prehľad o tom, čo sa v súbore nachádza.</p>
<ul style="font-family: 'Segoe UI', Roboto, sans-serif; color: #1f2937; line-height: 1.7; margin-top: 6px;">
<li>zobrazte názvy stĺpcov a dátové typy, použite <span style="background-color: #e5e7eb; color: #111827; font-family: monospace; padding: 2px 5px; border-radius: 4px;">info()</span> a <span style="background-color: #e5e7eb; color: #111827; font-family: monospace; padding: 2px 5px; border-radius: 4px;">describe(include='all')</span>,</li>
<li>spočítajte chýbajúce hodnoty v jednotlivých stĺpcoch, zistite počet unikátnych hodnôt v kategóriách <span style="background-color: #e5e7eb; color: #111827; font-family: monospace; padding: 2px 5px; border-radius: 4px;">Region</span> a <span style="background-color: #e5e7eb; color: #111827; font-family: monospace; padding: 2px 5px; border-radius: 4px;">Product</span>.</li>
</ul>
<div
  style="margin-top: 12px; background-color: #f9fafb; border-left: 4px solid #60a5fa; padding: 12px; border-radius: 4px;">
  💡 <strong>Pomôcka:</strong> Audit znamená, že si dataset najprv „zmapujete“.
Zaujíma vás napríklad počet riadkov, názvy stĺpcov, dátové typy, počet chýbajúcich hodnôt
a nečakané kategórie.
<br><br>
Užitočné príkazy:
<pre style="background: #f9fafb; padding: 14px; border-radius: 8px; overflow: auto; font-size: 14px; line-height: 1.5; font-family: ui-monospace, SFMono-Regular, Menlo, monospace; margin: 10px 0 14px;">df.info()
df.describe(include="all")
df.isna().sum()
df["column"].value_counts(dropna=False)</pre>
Cieľom tejto úlohy ešte nie je nič opravovať. Najprv si vytvorte obraz o tom, aké problémy v dátach vôbec máte.
</div>

In [2]:
print(df.columns.tolist())
df.info()
display(df.describe(include="all"))
print("Chýbajúce hodnoty:")
print(df.isna().sum())
for column in ["Region", "Product"]:
    print(column, "– počet unikátnych hodnôt:", df[column].nunique())
    print(df[column].value_counts(dropna=False))

['OrderID', 'CustomerName', 'Region', 'Product', 'Quantity', 'SalesAmount', 'Discount', 'OrderDate', 'DeliveryDate', 'PhoneNumber']
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 200 entries, 0 to 199
Data columns (total 10 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   OrderID       200 non-null    string
 1   CustomerName  178 non-null    string
 2   Region        200 non-null    string
 3   Product       200 non-null    string
 4   Quantity      200 non-null    string
 5   SalesAmount   194 non-null    string
 6   Discount      188 non-null    string
 7   OrderDate     200 non-null    string
 8   DeliveryDate  199 non-null    string
 9   PhoneNumber   162 non-null    string
dtypes: string(10)
memory usage: 15.8 KB

,OrderID,CustomerName,Region,Product,Quantity,SalesAmount,Discount,OrderDate,DeliveryDate,PhoneNumber
count,200,178,200,200,200,194,188,200,199,162
unique,188,20,8,7,17,180,11,194,131,8
top,ORD1025,Ibrahim Musa,West,lap top,8,one hundred,30,15-01-2025,12/31/24,+44 20 7946 0958
freq,3,14,35,35,22,10,28,6,6,25

Chýbajúce hodnoty:
OrderID          0
CustomerName    22
Region           0
Product          0
Quantity         0
SalesAmount      6
Discount        12
OrderDate        0
DeliveryDate     1
PhoneNumber     38
dtype: int64
Region – počet unikátnych hodnôt: 8
Region
West      35
South     29
North     27
north     23
East      23
Nrth      23
SOUTH     21
Souht     19
Name: count, dtype: Int64
Product – počet unikátnych hodnôt: 7
Product
lap top      35
Accessory    32
Unknown      31
phone        30
Tablet       27
Phone        24
Laptop       21
Name: count, dtype: Int64

<h2 style="margin: 24px 0 16px; font-size: 20px; font-weight: 600; font-family: 'Segoe UI', Roboto, sans-serif; color: #111827; border-bottom: 2px solid #e5e7eb; padding-bottom: 6px;">💻 Úloha 3 – Kontrola schémy a povinných stĺpcov</h2>
<p style="font-family: 'Segoe UI', Roboto, sans-serif; color: #1f2937; line-height: 1.65; margin: 8px 0 12px;">Pred ďalším spracovaním overte, či vstup obsahuje všetky stĺpce, ktoré pipeline očakáva. Ak niektorý chýba, spracovanie má skončiť s jasnou chybovou hláškou.</p>
<ul style="font-family: 'Segoe UI', Roboto, sans-serif; color: #1f2937; line-height: 1.7; margin-top: 6px;">
<li>vytvorte zoznam očakávaných stĺpcov, porovnajte ho so skutočnými stĺpcami datasetu, pri chýbajúcom stĺpci vyvolajte výnimku.</li>
</ul>
<div
  style="margin-top: 12px; background-color: #f9fafb; border-left: 4px solid #60a5fa; padding: 12px; border-radius: 4px;">
  💡 <strong>Pomôcka:</strong> Pipeline často očakáva presnú schému. Môžete si preto vytvoriť
zoznam povinných názvov stĺpcov a porovnať ho s <span style="background-color: #e5e7eb; color: #111827; font-family: monospace; padding: 2px 5px; border-radius: 4px;">df.columns</span>.
<br><br>
Princíp:
<pre style="background: #f9fafb; padding: 14px; border-radius: 8px; overflow: auto; font-size: 14px; line-height: 1.5; font-family: ui-monospace, SFMono-Regular, Menlo, monospace; margin: 10px 0 14px;">required = ["id", "date", "amount"]
# zistite, ktoré z required chýbajú v df.columns</pre>
Ak kritický stĺpec chýba, je vhodnejšie spracovanie zastaviť pomocou
<span style="background-color: #e5e7eb; color: #111827; font-family: monospace; padding: 2px 5px; border-radius: 4px;">raise ValueError(...)</span> než pokračovať s neúplnými dátami.
</div>

In [3]:
required_columns = ["OrderID", "CustomerName", "Region", "Product", "Quantity",
                    "SalesAmount", "Discount", "OrderDate", "DeliveryDate", "PhoneNumber"]
missing_columns = [column for column in required_columns if column not in df.columns]
if missing_columns:
    raise ValueError(f"Chýbajú povinné stĺpce: {missing_columns}")
print("Všetky požadované stĺpce sú prítomné.")
work = df.copy()
flags = pd.DataFrame(index=df.index)

Všetky požadované stĺpce sú prítomné.

<h2 style="margin: 24px 0 16px; font-size: 20px; font-weight: 600; font-family: 'Segoe UI', Roboto, sans-serif; color: #111827; border-bottom: 2px solid #e5e7eb; padding-bottom: 6px;">💻 Úloha 4 – Validácia identifikátora objednávky</h2>
<p style="font-family: 'Segoe UI', Roboto, sans-serif; color: #1f2937; line-height: 1.65; margin: 8px 0 12px;">Stĺpec <span style="background-color: #e5e7eb; color: #111827; font-family: monospace; padding: 2px 5px; border-radius: 4px;">OrderID</span> je kľúčový identifikátor záznamu. Overte jeho formát a unikátnosť.</p>
<ul style="font-family: 'Segoe UI', Roboto, sans-serif; color: #1f2937; line-height: 1.7; margin-top: 6px;">
<li>nájdite hodnoty, ktoré nezodpovedajú formátu <span style="background-color: #e5e7eb; color: #111827; font-family: monospace; padding: 2px 5px; border-radius: 4px;">ORD</span> + 4 číslice,</li>
<li>nájdite všetky riadky, ktorých <span style="background-color: #e5e7eb; color: #111827; font-family: monospace; padding: 2px 5px; border-radius: 4px;">OrderID</span> sa vyskytuje viac než raz,</li>
<li>duplicitné riadky zatiaľ nemažte, iba ich oddeľte na kontrolu.</li>
</ul>
<div
  style="margin-top: 12px; background-color: #f9fafb; border-left: 4px solid #60a5fa; padding: 12px; border-radius: 4px;">
  💡 <strong>Pomôcka:</strong> Identifikátor má dve samostatné požiadavky:
<strong>správny formát</strong> a <strong>unikátnosť</strong>.
<br><br>
Na formát sa hodí:
<pre style="background: #f9fafb; padding: 14px; border-radius: 8px; overflow: auto; font-size: 14px; line-height: 1.5; font-family: ui-monospace, SFMono-Regular, Menlo, monospace; margin: 10px 0 14px;">series.str.match(r"^ABC\d{3}$", na=False)</pre>
Toto je iba príklad iného formátu. Pre vaše <span style="background-color: #e5e7eb; color: #111827; font-family: monospace; padding: 2px 5px; border-radius: 4px;">OrderID</span> si zostavte vlastný regex.
<br><br>
Na duplicity sa hodí:
<pre style="background: #f9fafb; padding: 14px; border-radius: 8px; overflow: auto; font-size: 14px; line-height: 1.5; font-family: ui-monospace, SFMono-Regular, Menlo, monospace; margin: 10px 0 14px;">df.duplicated("id", keep=False)</pre>
Najprv si duplicitné riadky zobrazte. Neodstraňujte ich automaticky.
</div>

In [4]:
flags["invalid_order_id"] = ~df["OrderID"].str.fullmatch(r"ORD[0-9]{4}", na=False)
flags["duplicate_order_id"] = df["OrderID"].notna() & df.duplicated("OrderID", keep=False)
invalid_ids = df.loc[flags["invalid_order_id"]].copy()
duplicate_records = df.loc[flags["duplicate_order_id"]].copy()
print("Neplatné identifikátory:")
display(invalid_ids)
print("Všetky záznamy s duplicitným identifikátorom:")
display(duplicate_records)

Neplatné identifikátory:

Empty DataFrame
Columns: [OrderID, CustomerName, Region, Product, Quantity, SalesAmount, Discount, OrderDate, DeliveryDate, PhoneNumber]
Index: []

Všetky záznamy s duplicitným identifikátorom:

,OrderID,CustomerName,Region,Product,Quantity,SalesAmount,Discount,OrderDate,DeliveryDate,PhoneNumber
14,ORD1186,Charlie Lee,West,Phone,8,572.23,10,15-01-2025,2025-01-14,2025550185
32,ORD1035,Tina Zhang,SOUTH,Laptop,6,<NA>,150,2025-02-25,2025-03-11,+44 20 7946 0958
34,ORD1150,<NA>,North,phone,10,2381.85,<NA>,2025-05-31,2025-06-02,(202) 555-0189
42,ORD1186,David King,north,Phone,4,4496.56,30,2025-02-08,2025-02-15,12345
57,ORD1098,Kevin Patel,South,Accessory,0,4171.79,30,2025-04-09,2025-04-23,+44 20 7946 0958
62,ORD1031,Fatima Yusuf,SOUTH,Tablet,7,1236.1,15,2025-02-01,12/31/24,12345
64,ORD1035,Ella Brown,South,Laptop,6,2498.38,15,2025-02-05,2025-02-15,<NA>
75,ORD1080,Ella Brown,Souht,lap top,1,2940.19,15,2025-04-24,2025-05-04,+2348012345678
84,ORD1150,Ella Brown,North,Tablet,2,7696USD,-5,2025-07-11,2025-07-25,08012345678
90,ORD1022,George Miller,Souht,Unknown,8,2714.26,0,2025-01-23,2025-01-27,(202) 555-0189
104,ORD1109,<NA>,north,lap top,1,4856.04,20,2025-04-20,2025-04-23,<NA>
108,ORD1022,Ibrahim Musa,SOUTH,Unknown,2,4152.49,20,2025-04-23,2025-04-25,+44 20 7946 0958
124,ORD1025,Nina Roberts,Nrth,Laptop,1,470.09,30,2025-01-26,2025-01-30,+1-202-555-0178
126,ORD1035,Hannah Davis,Souht,Unknown,5,2082.64,10,2025-07-04,2025-07-16,2025550185
137,ORD1098,George Miller,West,phone,8,321.54,30,04/16/2025,2025-04-29,2025550185
144,ORD1080,Charlie Lee,East,lap top,-1,1337.0,5,2025-03-22,12/31/24,+2348012345678
152,ORD1025,Ibrahim Musa,SOUTH,Tablet,7,3253.21,30,2025-03-31,2025-04-05,+1-202-555-0178
160,ORD1109,Tina Zhang,Souht,Tablet,5,1008USD,-5,2025/02/30,2025-13-40,+1-202-555-0178
165,ORD1192,<NA>,Nrth,Accessory,10,"$4,167",10,2025-02-24,2025-03-07,+1-202-555-0178
174,ORD1031,Fatima Yusuf,South,Unknown,2,535.93,25,06/10/2025,2025-06-21,<NA>
175,ORD1192,Ella Brown,SOUTH,phone,7,"$1,461",<NA>,2025-07-12,2025-07-23,(202) 555-0189
178,ORD1025,Alice Johnson,north,Phone,8,4287USD,10,2025-06-07,2025-06-20,(202) 555-0189

<h2 style="margin: 24px 0 16px; font-size: 20px; font-weight: 600; font-family: 'Segoe UI', Roboto, sans-serif; color: #111827; border-bottom: 2px solid #e5e7eb; padding-bottom: 6px;">💻 Úloha 5 – Zjednotenie kategórií</h2>
<p style="font-family: 'Segoe UI', Roboto, sans-serif; color: #1f2937; line-height: 1.65; margin: 8px 0 12px;">Skontrolujte stĺpce <span style="background-color: #e5e7eb; color: #111827; font-family: monospace; padding: 2px 5px; border-radius: 4px;">Region</span> a <span style="background-color: #e5e7eb; color: #111827; font-family: monospace; padding: 2px 5px; border-radius: 4px;">Product</span>. Hodnoty, ktoré významovo označujú to isté, zjednoťte do jedného tvaru.</p>
<ul style="font-family: 'Segoe UI', Roboto, sans-serif; color: #1f2937; line-height: 1.7; margin-top: 6px;">
<li>odstráňte nadbytočné medzery, zjednoťte veľkosť písmen, opravte zjavné preklepy, po transformácii overte, že zostali iba povolené kategórie.</li>
</ul>
<div
  style="margin-top: 12px; background-color: #f9fafb; border-left: 4px solid #60a5fa; padding: 12px; border-radius: 4px;">
  💡 <strong>Pomôcka:</strong> Pri kategóriách je vhodné oddeliť
<strong>normalizáciu</strong> od <strong>opravy významu</strong>.
<br><br>
Normalizácia môže vyzerať napríklad:
<pre style="background: #f9fafb; padding: 14px; border-radius: 8px; overflow: auto; font-size: 14px; line-height: 1.5; font-family: ui-monospace, SFMono-Regular, Menlo, monospace; margin: 10px 0 14px;">series.str.strip().str.lower()</pre>
Potom si môžete pripraviť slovník variantov:
<pre style="background: #f9fafb; padding: 14px; border-radius: 8px; overflow: auto; font-size: 14px; line-height: 1.5; font-family: ui-monospace, SFMono-Regular, Menlo, monospace; margin: 10px 0 14px;">mapping = {
    "n": "North",
    "north ": "North"
}</pre>
Pri hodnote, ktorej význam si neviete jednoznačne odvodiť, ju radšej označte ako problém namiesto toho, aby ste ju „uhádli“.
</div>

In [5]:
region_mapping = {"north": "North", "nrth": "North", "south": "South",
                  "souht": "South", "east": "East", "west": "West"}
product_mapping = {"laptop": "Laptop", "lap top": "Laptop", "phone": "Phone",
                   "tablet": "Tablet", "accessory": "Accessory"}
allowed_regions = {"North", "South", "East", "West"}
allowed_products = {"Laptop", "Phone", "Tablet", "Accessory"}
work["Region"] = df["Region"].str.strip().str.lower().map(region_mapping).astype("string")
work["Product"] = df["Product"].str.strip().str.lower().map(product_mapping).astype("string")
flags["invalid_region"] = ~work["Region"].isin(allowed_regions)
flags["invalid_product"] = ~work["Product"].isin(allowed_products)
print(work["Region"].value_counts(dropna=False))
print(work["Product"].value_counts(dropna=False))
display(df.loc[flags["invalid_region"] | flags["invalid_product"], ["Region", "Product"]])

Region
North    73
South    69
West     35
East     23
Name: count, dtype: Int64
Product
Laptop       56
Phone        54
Accessory    32
<NA>         31
Tablet       27
Name: count, dtype: Int64

     Region  Product
0     South  Unknown
5     North  Unknown
8     South  Unknown
18     Nrth  Unknown
21    North  Unknown
24    north  Unknown
49    Souht  Unknown
51     West  Unknown
55    North  Unknown
58     West  Unknown
63    Souht  Unknown
76   SOUTH   Unknown
82    South  Unknown
90    Souht  Unknown
93     West  Unknown
108  SOUTH   Unknown
117   north  Unknown
118   Souht  Unknown
126   Souht  Unknown
132   South  Unknown
135    Nrth  Unknown
141    West  Unknown
145   South  Unknown
149    West  Unknown
151   north  Unknown
157    Nrth  Unknown
169  SOUTH   Unknown
174   South  Unknown
177   Souht  Unknown
185   Souht  Unknown
191    West  Unknown

<h2 style="margin: 24px 0 16px; font-size: 20px; font-weight: 600; font-family: 'Segoe UI', Roboto, sans-serif; color: #111827; border-bottom: 2px solid #e5e7eb; padding-bottom: 6px;">💻 Úloha 6 – Číselné hodnoty a konverzné chyby</h2>
<p style="font-family: 'Segoe UI', Roboto, sans-serif; color: #1f2937; line-height: 1.65; margin: 8px 0 12px;">Stĺpce <span style="background-color: #e5e7eb; color: #111827; font-family: monospace; padding: 2px 5px; border-radius: 4px;">Quantity</span>, <span style="background-color: #e5e7eb; color: #111827; font-family: monospace; padding: 2px 5px; border-radius: 4px;">SalesAmount</span> a <span style="background-color: #e5e7eb; color: #111827; font-family: monospace; padding: 2px 5px; border-radius: 4px;">Discount</span> obsahujú hodnoty, ktoré nie sú uložené konzistentne.</p>
<ul style="font-family: 'Segoe UI', Roboto, sans-serif; color: #1f2937; line-height: 1.7; margin-top: 6px;">
<li>identifikujte hodnoty, ktoré sa nedajú priamo skonvertovať na číslo, odstráňte formátovacie znaky, pri ktorých je význam jednoznačný (napr. mena alebo oddeľovač tisícov), konverziu vykonajte s <span style="background-color: #e5e7eb; color: #111827; font-family: monospace; padding: 2px 5px; border-radius: 4px;">errors='coerce'</span> a následne odlíšte pôvodne chýbajúce hodnoty od hodnôt, ktoré sa stali <span style="background-color: #e5e7eb; color: #111827; font-family: monospace; padding: 2px 5px; border-radius: 4px;">NaN</span> kvôli chybe konverzie,</li>
<li>overte business pravidlá pre rozsah hodnôt.</li>
</ul>
<div
  style="margin-top: 12px; background-color: #f9fafb; border-left: 4px solid #60a5fa; padding: 12px; border-radius: 4px;">
  💡 <strong>Pomôcka:</strong> Číselný stĺpec môže obsahovať napríklad medzery,
symbol meny alebo textové hodnoty. Najprv odstráňte iba tie znaky, pri ktorých je význam jasný.
<br><br>
Príklad:
<pre style="background: #f9fafb; padding: 14px; border-radius: 8px; overflow: auto; font-size: 14px; line-height: 1.5; font-family: ui-monospace, SFMono-Regular, Menlo, monospace; margin: 10px 0 14px;">cleaned = series.str.replace("$", "", regex=False)
numeric = pd.to_numeric(cleaned, errors="coerce")</pre>
Po konverzii hľadajte <span style="background-color: #e5e7eb; color: #111827; font-family: monospace; padding: 2px 5px; border-radius: 4px;">NaN</span> a následne overte business pravidlá,
napríklad kladnosť alebo povolený interval.
<br><br>
Pozor: <span style="background-color: #e5e7eb; color: #111827; font-family: monospace; padding: 2px 5px; border-radius: 4px;">NaN</span> po konverzii môže znamenať niečo iné než pôvodne chýbajúca hodnota.
</div>

In [6]:
for column in ["Quantity", "SalesAmount", "Discount"]:
    original = df[column].str.strip()
    missing = original.isna() | original.eq("").fillna(False)
    direct = pd.to_numeric(original, errors="coerce")
    print(column, "– hodnoty, ktoré sa nedajú priamo skonvertovať:")
    print(original.loc[~missing & direct.isna()].unique())
    formatted = original.copy()
    if column == "SalesAmount":
        formatted = formatted.str.replace(r"^\$|USD$", "", regex=True).str.strip()
        thousands = formatted.str.fullmatch(r"[+-]?[0-9]{1,3}(,[0-9]{3})+(\.[0-9]+)?", na=False)
        formatted.loc[thousands] = formatted.loc[thousands].str.replace(",", "", regex=False)
    work[column] = pd.to_numeric(formatted, errors="coerce").astype("Float64")
    flags[f"missing_{column}"] = missing
    flags[f"conversion_{column}"] = ~missing & work[column].isna()

flags["invalid_quantity_range"] = (work["Quantity"].notna() &
    ((work["Quantity"] <= 0) | (work["Quantity"] % 1 != 0))).fillna(False)
flags["invalid_sales_range"] = (work["SalesAmount"].notna() &
    ((work["SalesAmount"] <= 0) | ~np.isfinite(work["SalesAmount"]))).fillna(False)
flags["invalid_discount_range"] = (work["Discount"].notna() &
    ~work["Discount"].between(0, 100)).fillna(False)
display(work[["Quantity", "SalesAmount", "Discount"]].head(10))
print(flags.filter(regex="missing_|conversion_|range").sum())

Quantity – hodnoty, ktoré sa nedajú priamo skonvertovať:
<StringArray>
['five', 'ten']
Length: 2, dtype: string
SalesAmount – hodnoty, ktoré sa nedajú priamo skonvertovať:
<StringArray>
[     '840USD',          '??',      '$1,165',      '$1,325', 'one hundred',
      '$1,339',      '$3,410',     '8488USD',      '$1,143',      '$2,952',
     '3347USD',        '$567',     '9877USD',     '5448USD',     '7627USD',
     '7891USD',     '2464USD',     '7696USD',      '$2,192',      '$3,267',
      '$4,609',     '9677USD',     '1008USD',        '$186',      '$4,167',
     '8259USD',      '$1,461',      '$4,545',     '4287USD',      '$4,868',
     '3736USD',      '$2,987',     '6305USD',     '6002USD']
Length: 34, dtype: string
Discount – hodnoty, ktoré sa nedajú priamo skonvertovať:
<StringArray>
['ten']
Length: 1, dtype: string

   Quantity  SalesAmount  Discount
0      -1.0      2710.16      15.0
1       7.0        840.0      20.0
2       6.0      1805.15      15.0
3       0.0         <NA>       5.0
4       9.0      3083.23       5.0
5      -1.0      3876.36      10.0
6       3.5      2518.94      <NA>
7       1.0      1380.89      10.0
8       9.0      3710.03      15.0
9       2.0         <NA>      15.0

missing_Quantity           0
conversion_Quantity        5
missing_SalesAmount        6
conversion_SalesAmount    16
missing_Discount          12
conversion_Discount        9
invalid_quantity_range    24
invalid_sales_range        0
invalid_discount_range     8
dtype: Int64

<h2 style="margin: 24px 0 16px; font-size: 20px; font-weight: 600; font-family: 'Segoe UI', Roboto, sans-serif; color: #111827; border-bottom: 2px solid #e5e7eb; padding-bottom: 6px;">💻 Úloha 7 – Dátumy a logická konzistencia</h2>
<p style="font-family: 'Segoe UI', Roboto, sans-serif; color: #1f2937; line-height: 1.65; margin: 8px 0 12px;">Skonvertujte <span style="background-color: #e5e7eb; color: #111827; font-family: monospace; padding: 2px 5px; border-radius: 4px;">OrderDate</span> a <span style="background-color: #e5e7eb; color: #111827; font-family: monospace; padding: 2px 5px; border-radius: 4px;">DeliveryDate</span> na dátumový typ a skontrolujte nielen formát, ale aj vzájomnú logiku.</p>
<ul style="font-family: 'Segoe UI', Roboto, sans-serif; color: #1f2937; line-height: 1.7; margin-top: 6px;">
<li>neplatné dátumy preveďte na <span style="background-color: #e5e7eb; color: #111827; font-family: monospace; padding: 2px 5px; border-radius: 4px;">NaT</span>,</li>
<li>nájdite záznamy, v ktorých sa dátum nepodarilo skonvertovať,nájdite objednávky, pri ktorých je <span style="background-color: #e5e7eb; color: #111827; font-family: monospace; padding: 2px 5px; border-radius: 4px;">DeliveryDate</span> skorší než <span style="background-color: #e5e7eb; color: #111827; font-family: monospace; padding: 2px 5px; border-radius: 4px;">OrderDate</span>.</li>
</ul>
<div
  style="margin-top: 12px; background-color: #f9fafb; border-left: 4px solid #60a5fa; padding: 12px; border-radius: 4px;">
  💡 <strong>Pomôcka:</strong> Prvý krok je bezpečná konverzia:
<pre style="background: #f9fafb; padding: 14px; border-radius: 8px; overflow: auto; font-size: 14px; line-height: 1.5; font-family: ui-monospace, SFMono-Regular, Menlo, monospace; margin: 10px 0 14px;">pd.to_datetime(series, errors="coerce")</pre>
Neplatné hodnoty sa zmenia na <span style="background-color: #e5e7eb; color: #111827; font-family: monospace; padding: 2px 5px; border-radius: 4px;">NaT</span>.
Potom však ešte musíte skontrolovať logiku medzi dvoma dátumami.
<br><br>
Príklad logickej kontroly:
<pre style="background: #f9fafb; padding: 14px; border-radius: 8px; overflow: auto; font-size: 14px; line-height: 1.5; font-family: ui-monospace, SFMono-Regular, Menlo, monospace; margin: 10px 0 14px;">end_date < start_date</pre>
Takýto záznam môže obsahovať dva úplne platné dátumy, ale ich vzájomný vzťah je chybný.
</div>

In [7]:
def parse_dates(series):
    text = series.str.strip()
    result = pd.Series(pd.NaT, index=series.index, dtype="datetime64[ns]")
    for date_format in ["%Y-%m-%d", "%d-%m-%Y", "%m/%d/%Y", "%m/%d/%y", "%Y/%m/%d"]:
        parsed = pd.to_datetime(text, format=date_format, errors="coerce")
        result = result.fillna(parsed)
    return result

for column in ["OrderDate", "DeliveryDate"]:
    work[column] = parse_dates(df[column])
    flags[f"invalid_{column}"] = work[column].isna()
    print(column, "– chýbajúce alebo neplatné dátumy:")
    display(df.loc[flags[f"invalid_{column}"], ["OrderID", column]])
flags["delivery_before_order"] = work["DeliveryDate"] < work["OrderDate"]
print("Dodanie pred objednávkou:")
display(work.loc[flags["delivery_before_order"], ["OrderID", "OrderDate", "DeliveryDate"]])

OrderDate – chýbajúce alebo neplatné dátumy:

     OrderID   OrderDate
59   ORD1096  2025-13-40
118  ORD1163  2025/02/30
160  ORD1109  2025/02/30

DeliveryDate – chýbajúce alebo neplatné dátumy:

     OrderID DeliveryDate
0    ORD1095   2024-02-30
13   ORD1078   2024-02-30
28   ORD1125   2025-00-10
59   ORD1096   2025-13-40
69   ORD1136   2025-00-10
71   ORD1127   2025-00-10
118  ORD1163         <NA>
150  ORD1176   2025-00-10
160  ORD1109   2025-13-40
196  ORD1014   2025-00-10

Dodanie pred objednávkou:

     OrderID  OrderDate DeliveryDate
11   ORD1182 2025-07-02   2024-12-31
12   ORD1165 2025-06-15   2025-06-13
14   ORD1186 2025-01-15   2025-01-14
29   ORD1132 2025-05-13   2025-05-09
30   ORD1009 2025-01-10   2025-01-06
44   ORD1122 2025-05-03   2025-04-30
62   ORD1031 2025-02-01   2024-12-31
63   ORD1012 2025-01-13   2025-01-09
68   ORD1090 2025-04-01   2025-03-28
70   ORD1051 2025-02-21   2025-02-19
85   ORD1085 2025-03-27   2024-12-31
98   ORD1027 2025-01-28   2024-12-31
101  ORD1032 2025-02-02   2025-01-29
129  ORD1039 2025-02-09   2025-02-04
132  ORD1094 2025-04-05   2025-04-01
144  ORD1080 2025-03-22   2024-12-31
149  ORD1083 2025-03-25   2024-12-31
154  ORD1013 2025-01-14   2025-01-13

<h2 style="margin: 24px 0 16px; font-size: 20px; font-weight: 600; font-family: 'Segoe UI', Roboto, sans-serif; color: #111827; border-bottom: 2px solid #e5e7eb; padding-bottom: 6px;">💻 Úloha 8 – Validácia telefónneho čísla</h2>
<p style="font-family: 'Segoe UI', Roboto, sans-serif; color: #1f2937; line-height: 1.65; margin: 8px 0 12px;">Telefónne čísla sú v súbore zapísané v rôznych formátoch. Stĺpec je nepovinný, ale vyplnená hodnota musí byť validná.</p>
<ul style="font-family: 'Segoe UI', Roboto, sans-serif; color: #1f2937; line-height: 1.7; margin-top: 6px;">
<li>odstráňte medzery, zátvorky, pomlčky a znak <span style="background-color: #e5e7eb; color: #111827; font-family: monospace; padding: 2px 5px; border-radius: 4px;">+</span>,</li>
<li>ponechajte iba číslice, za platné považujte hodnoty s 10 až 15 číslicami, neplatné, ale vyplnené telefónne čísla označte samostatným validačným príznakom.</li>
</ul>
<div
  style="margin-top: 12px; background-color: #f9fafb; border-left: 4px solid #60a5fa; padding: 12px; border-radius: 4px;">
  💡 <strong>Pomôcka:</strong> Telefónne čísla môžu mať rôzne formátovanie.
Najprv preto vytvorte pomocnú hodnotu, v ktorej zostanú iba číslice.
<pre style="background: #f9fafb; padding: 14px; border-radius: 8px; overflow: auto; font-size: 14px; line-height: 1.5; font-family: ui-monospace, SFMono-Regular, Menlo, monospace; margin: 10px 0 14px;">digits = series.str.replace(r"\D", "", regex=True)</pre>
Potom môžete kontrolovať dĺžku pomocou <span style="background-color: #e5e7eb; color: #111827; font-family: monospace; padding: 2px 5px; border-radius: 4px;">str.len()</span>.
<br><br>
Rozlišujte medzi <strong>chýbajúcou hodnotou</strong> a <strong>vyplnenou, ale neplatnou hodnotou</strong>.
Keď je telefón nepovinný, prázdna hodnota nemusí byť chyba.
</div>

In [8]:
phone = df["PhoneNumber"].str.strip()
phone_filled = phone.notna() & phone.ne("").fillna(False)
phone_digits = phone.str.replace(r"\D", "", regex=True)
flags["invalid_phone"] = phone_filled & ~phone_digits.str.fullmatch(r"[0-9]{10,15}", na=False)
work["PhoneNumber"] = phone_digits.where(phone_filled & ~flags["invalid_phone"], pd.NA)
display(pd.DataFrame({"pôvodné_číslo": phone, "vyčistené_číslo": work["PhoneNumber"],
                      "neplatný_telefón": flags["invalid_phone"]}).head(15))

      pôvodné_číslo vyčistené_číslo  neplatný_telefón
0    +2348012345678   2348012345678             False
1             12345            <NA>              True
2          555-018X            <NA>              True
3   +1-202-555-0178     12025550178             False
4              <NA>            <NA>             False
5   +1-202-555-0178     12025550178             False
6    (202) 555-0189      2025550189             False
7              <NA>            <NA>             False
8   +1-202-555-0178     12025550178             False
9             12345            <NA>              True
10      08012345678     08012345678             False
11         555-018X            <NA>              True
12  +1-202-555-0178     12025550178             False
13            12345            <NA>              True
14       2025550185      2025550185             False

<h2 style="margin: 24px 0 16px; font-size: 20px; font-weight: 600; font-family: 'Segoe UI', Roboto, sans-serif; color: #111827; border-bottom: 2px solid #e5e7eb; padding-bottom: 6px;">💻 Úloha 9 – Vytvorenie validačného reportu</h2>
<p style="font-family: 'Segoe UI', Roboto, sans-serif; color: #1f2937; line-height: 1.65; margin: 8px 0 12px;">Namiesto toho, aby boli jednotlivé kontroly roztrúsené po notebooku, vytvorte jeden prehľad, ktorý ukáže počet nájdených problémov podľa typu.</p>
<ul style="font-family: 'Segoe UI', Roboto, sans-serif; color: #1f2937; line-height: 1.7; margin-top: 6px;">
<li>vytvorte validačné príznaky pre jednotlivé pravidlá, zostavte z nich tabuľku <span style="background-color: #e5e7eb; color: #111827; font-family: monospace; padding: 2px 5px; border-radius: 4px;">validation_report</span>,</li>
<li>pri každom pravidle zobrazte počet chybných riadkov.</li>
</ul>
<div
  style="margin-top: 12px; background-color: #f9fafb; border-left: 4px solid #60a5fa; padding: 12px; border-radius: 4px;">
  💡 <strong>Pomôcka:</strong> Dobrá validačná pipeline si pri každom pravidle vytvorí boolean príznak:
<span style="background-color: #e5e7eb; color: #111827; font-family: monospace; padding: 2px 5px; border-radius: 4px;">True</span> = problém, <span style="background-color: #e5e7eb; color: #111827; font-family: monospace; padding: 2px 5px; border-radius: 4px;">False</span> = v poriadku.
<br><br>
Napríklad všeobecne:
<pre style="background: #f9fafb; padding: 14px; border-radius: 8px; overflow: auto; font-size: 14px; line-height: 1.5; font-family: ui-monospace, SFMono-Regular, Menlo, monospace; margin: 10px 0 14px;">flags["invalid_amount"] = ...
flags["invalid_date"] = ...</pre>
Keď máte pravidlá pokope, <span style="background-color: #e5e7eb; color: #111827; font-family: monospace; padding: 2px 5px; border-radius: 4px;">sum()</span> vám dá počet chýb pre každý typ.
Takto získate report, ktorý sa dá neskôr logovať alebo monitorovať.
</div>

In [9]:
flags = flags.fillna(False).astype(bool)
validation_report = flags.sum().rename_axis("rule").reset_index(name="error_count")
validation_report["severity"] = validation_report["rule"].map(
    lambda rule: "warning" if rule == "invalid_phone" else "critical")
display(validation_report)

                      rule  error_count  severity
0         invalid_order_id            0  critical
1       duplicate_order_id           22  critical
2           invalid_region            0  critical
3          invalid_product           31  critical
4         missing_Quantity            0  critical
5      conversion_Quantity            5  critical
6      missing_SalesAmount            6  critical
7   conversion_SalesAmount           16  critical
8         missing_Discount           12  critical
9      conversion_Discount            9  critical
10  invalid_quantity_range           24  critical
11     invalid_sales_range            0  critical
12  invalid_discount_range            8  critical
13       invalid_OrderDate            3  critical
14    invalid_DeliveryDate           10  critical
15   delivery_before_order           18  critical
16           invalid_phone           34   warning

<h2 style="margin: 24px 0 16px; font-size: 20px; font-weight: 600; font-family: 'Segoe UI', Roboto, sans-serif; color: #111827; border-bottom: 2px solid #e5e7eb; padding-bottom: 6px;">💻 Úloha 10 – Oddelenie validných a problémových záznamov</h2>
<p style="font-family: 'Segoe UI', Roboto, sans-serif; color: #1f2937; line-height: 1.65; margin: 8px 0 12px;">Nie všetky chyby majú rovnakú závažnosť. Navrhnite, ktoré chyby považujete za kritické pre ďalšie spracovanie a ktoré môžu zostať iba ako upozornenie.</p>
<ul style="font-family: 'Segoe UI', Roboto, sans-serif; color: #1f2937; line-height: 1.7; margin-top: 6px;">
<li>vytvorte masku kritických chýb, rozdeľte dáta na <span style="background-color: #e5e7eb; color: #111827; font-family: monospace; padding: 2px 5px; border-radius: 4px;">clean_data</span> a <span style="background-color: #e5e7eb; color: #111827; font-family: monospace; padding: 2px 5px; border-radius: 4px;">rejected_records</span>,</li>
<li>pri zamietnutých záznamoch zachovajte informáciu o dôvode zamietnutia.</li>
</ul>
<div
  style="margin-top: 12px; background-color: #f9fafb; border-left: 4px solid #60a5fa; padding: 12px; border-radius: 4px;">
  💡 <strong>Pomôcka:</strong> Ak má každý validačný test vlastný boolean stĺpec,
môžete sa na úroveň celého riadku opýtať:
<em>porušil tento riadok aspoň jedno kritické pravidlo?</em>
<br><br>
Na to sa hodí:
<pre style="background: #f9fafb; padding: 14px; border-radius: 8px; overflow: auto; font-size: 14px; line-height: 1.5; font-family: ui-monospace, SFMono-Regular, Menlo, monospace; margin: 10px 0 14px;">flags[critical_rules].any(axis=1)</pre>
Výsledkom je maska, ktorou môžete rozdeliť dáta na validné a problémové.
Pri problémových riadkoch je užitočné ponechať aj informáciu, ktoré pravidlá zlyhali.
</div>

In [10]:
critical_rules = [column for column in flags if column != "invalid_phone"]
critical_errors = flags[critical_rules].any(axis=1)
clean_data = work.loc[~critical_errors].copy()
rejected_records = df.loc[critical_errors].copy()
rejected_records["rejection_reasons"] = flags.loc[critical_errors, critical_rules].apply(
    lambda row: "; ".join(row.index[row]), axis=1)
rejected_records["invalid_phone"] = flags.loc[critical_errors, "invalid_phone"]
print("Čisté záznamy:", len(clean_data))
print("Zamietnuté záznamy:", len(rejected_records))
print("Telefón je nepovinný. Neplatný telefón je upozornenie a nahradím ho chýbajúcou hodnotou.")
print("Ostatné pravidlá sú kritické. Všetky záznamy s duplicitným ID nechávam na kontrolu.")
display(rejected_records.head())

Čisté záznamy: 84
Zamietnuté záznamy: 116
Telefón je nepovinný. Neplatný telefón je upozornenie a nahradím ho chýbajúcou hodnotou.
Ostatné pravidlá sú kritické. Všetky záznamy s duplicitným ID nechávam na kontrolu.

,OrderID,CustomerName,Region,Product,Quantity,SalesAmount,Discount,OrderDate,DeliveryDate,PhoneNumber,rejection_reasons,invalid_phone
0,ORD1095,Bob Smith,South,Unknown,-1,2710.16,15,2025-04-06,2024-02-30,+2348012345678,invalid_product; invalid_quantity_range; inval...,False
3,ORD1158,Ibrahim Musa,North,phone,0,<NA>,5,2025-06-08,2025-06-21,+1-202-555-0178,missing_SalesAmount; invalid_quantity_range,False
5,ORD1115,Rita Gomez,North,Unknown,-1,3876.36,10,2025-04-26,2025-05-04,+1-202-555-0178,invalid_product; invalid_quantity_range,False
6,ORD1069,Oluwaseun Adebayo,north,Tablet,3.5,2518.94,<NA>,2025-03-11,2025-03-15,(202) 555-0189,missing_Discount; invalid_quantity_range,False
8,ORD1174,Alice Johnson,South,Unknown,9,3710.03,15,2025-06-24,2025-07-02,+1-202-555-0178,invalid_product,False

<h2 style="margin: 24px 0 16px; font-size: 20px; font-weight: 600; font-family: 'Segoe UI', Roboto, sans-serif; color: #111827; border-bottom: 2px solid #e5e7eb; padding-bottom: 6px;">💻 Úloha 11 – Finalizácia čistej schémy</h2>
<p style="font-family: 'Segoe UI', Roboto, sans-serif; color: #1f2937; line-height: 1.65; margin: 8px 0 12px;">V dátach, ktoré prešli kritickou validáciou, nahraďte pôvodné nekonzistentné stĺpce vyčistenými verziami a ponechajte iba finálnu schému vhodnú na ďalšie spracovanie.</p>
<ul style="font-family: 'Segoe UI', Roboto, sans-serif; color: #1f2937; line-height: 1.7; margin-top: 6px;">
<li>nahraďte <span style="background-color: #e5e7eb; color: #111827; font-family: monospace; padding: 2px 5px; border-radius: 4px;">Region</span>, <span style="background-color: #e5e7eb; color: #111827; font-family: monospace; padding: 2px 5px; border-radius: 4px;">Product</span>, numerické a dátumové stĺpce vyčistenými hodnotami,</li>
<li>odstráňte pomocné stĺpce, nastavte vhodné dátové typy, znovu skontrolujte <span style="background-color: #e5e7eb; color: #111827; font-family: monospace; padding: 2px 5px; border-radius: 4px;">info()</span> a chýbajúce hodnoty.</li>
</ul>
<div
  style="margin-top: 12px; background-color: #f9fafb; border-left: 4px solid #60a5fa; padding: 12px; border-radius: 4px;">
  💡 <strong>Pomôcka:</strong> Po čistení máte často pôvodné aj pomocné stĺpce,
napríklad <span style="background-color: #e5e7eb; color: #111827; font-family: monospace; padding: 2px 5px; border-radius: 4px;">Region</span> a <span style="background-color: #e5e7eb; color: #111827; font-family: monospace; padding: 2px 5px; border-radius: 4px;">Region_clean</span>.
Finálny dataset by mal obsahovať iba stabilnú schému, ktorú očakáva ďalší krok pipeline.
<br>
Môžete vytvoriť nový DataFrame výberom a premenovaním vyčistených stĺpcov.
Na konci znovu použite <span style="background-color: #e5e7eb; color: #111827; font-family: monospace; padding: 2px 5px; border-radius: 4px;">info()</span> a
<span style="background-color: #e5e7eb; color: #111827; font-family: monospace; padding: 2px 5px; border-radius: 4px;">isna().sum()</span>.
</div>

In [11]:
clean_data = clean_data[required_columns].copy()
for column in ["OrderID", "CustomerName", "Region", "Product", "PhoneNumber"]:
    clean_data[column] = clean_data[column].astype("string")
clean_data["Quantity"] = clean_data["Quantity"].astype("Int64")
clean_data[["SalesAmount", "Discount"]] = clean_data[["SalesAmount", "Discount"]].astype("Float64")
clean_data.info()
print(clean_data.isna().sum())
display(clean_data.head())

<class 'pandas.core.frame.DataFrame'>
Index: 84 entries, 1 to 199
Data columns (total 10 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   OrderID       84 non-null     string
 1   CustomerName  74 non-null     string
 2   Region        84 non-null     string
 3   Product       84 non-null     string
 4   Quantity      84 non-null     Int64
 5   SalesAmount   84 non-null     Float64
 6   Discount      84 non-null     Float64
 7   OrderDate     84 non-null     datetime64[ns]
 8   DeliveryDate  84 non-null     datetime64[ns]
 9   PhoneNumber   50 non-null     string
dtypes: Float64(2), Int64(1), datetime64[ns](2), string(5)
memory usage: 7.5 KB
OrderID          0
CustomerName    10
Region           0
Product          0
Quantity         0
SalesAmount      0
Discount         0
OrderDate        0
DeliveryDate     0
PhoneNumber     34
dtype: int64

,OrderID,CustomerName,Region,Product,Quantity,SalesAmount,Discount,OrderDate,DeliveryDate,PhoneNumber
1,ORD1015,Charlie Lee,West,Phone,7,840.0,20.0,2025-01-16,2025-01-19,<NA>
2,ORD1030,Alice Johnson,West,Phone,6,1805.15,15.0,2025-01-31,2025-02-01,<NA>
4,ORD1128,Bob Smith,South,Laptop,9,3083.23,5.0,2025-05-09,2025-05-11,<NA>
7,ORD1170,Lola Ade,North,Accessory,1,1380.89,10.0,2025-06-20,2025-06-22,<NA>
10,ORD1066,David King,South,Tablet,8,2089.21,25.0,2025-03-08,2025-03-18,08012345678

<h2 style="margin: 24px 0 16px; font-size: 20px; font-weight: 600; font-family: 'Segoe UI', Roboto, sans-serif; color: #111827; border-bottom: 2px solid #e5e7eb; padding-bottom: 6px;">💻 Úloha 12 – Opätovná validácia a error handling</h2>
<p style="font-family: 'Segoe UI', Roboto, sans-serif; color: #1f2937; line-height: 1.65; margin: 8px 0 12px;">Po čistení vykonajte validačné pravidlá ešte raz. Ak kritické chyby stále zostali, pipeline nemá pokračovať ako keby bolo všetko v poriadku.</p>
<ul style="font-family: 'Segoe UI', Roboto, sans-serif; color: #1f2937; line-height: 1.7; margin-top: 6px;">
<li>vytvorte vlastnú výnimku <span style="background-color: #e5e7eb; color: #111827; font-family: monospace; padding: 2px 5px; border-radius: 4px;">DataValidationError</span> alebo použite vhodnú existujúcu výnimku,</li>
<li>overte unikátnosť <span style="background-color: #e5e7eb; color: #111827; font-family: monospace; padding: 2px 5px; border-radius: 4px;">OrderID</span>,</li>
<li>overte rozsahy číselných hodnôt a logiku dátumov, pri zlyhaní vyvolajte výnimku s informatívnou správou.</li>
</ul>
<div
  style="margin-top: 12px; background-color: #f9fafb; border-left: 4px solid #60a5fa; padding: 12px; border-radius: 4px;">
  💡 <strong>Pomôcka:</strong> Po čistení je vhodné najdôležitejšie pravidlá spustiť ešte raz.
Ak kritická podmienka stále neplatí, spracovanie sa má zastaviť.
<br><br>
Vlastná výnimka môže mať tvar:
<pre style="background: #f9fafb; padding: 14px; border-radius: 8px; overflow: auto; font-size: 14px; line-height: 1.5; font-family: ui-monospace, SFMono-Regular, Menlo, monospace; margin: 10px 0 14px;">class MyValidationError(Exception):
    pass</pre>
A pri zistení problému ju môžete vyvolať pomocou:
<pre style="background: #f9fafb; padding: 14px; border-radius: 8px; overflow: auto; font-size: 14px; line-height: 1.5; font-family: ui-monospace, SFMono-Regular, Menlo, monospace; margin: 10px 0 14px;">raise MyValidationError("...")</pre>
Nejde o to vyhadzovať výnimku pri každom NULL-e. Výnimka je vhodná vtedy, keď ďalšie spracovanie už nie je bezpečné.
</div>

In [12]:
class DataValidationError(Exception):
    pass

def validate_clean(data):
    checks = {
        "OrderID": data["OrderID"].str.fullmatch(r"ORD[0-9]{4}", na=False).all(),
        "unikátnosť OrderID": data["OrderID"].is_unique,
        "Region": data["Region"].isin(allowed_regions).all(),
        "Product": data["Product"].isin(allowed_products).all(),
        "Quantity": (data["Quantity"].notna() & (data["Quantity"] > 0) &
                     (data["Quantity"] % 1 == 0)).all(),
        "SalesAmount": (data["SalesAmount"].notna() & (data["SalesAmount"] > 0) &
                        np.isfinite(data["SalesAmount"])).all(),
        "Discount": (data["Discount"].notna() & data["Discount"].between(0, 100)).all(),
        "dátumy": (data["OrderDate"].notna() & data["DeliveryDate"].notna() &
                   (data["DeliveryDate"] >= data["OrderDate"])).all(),
        "PhoneNumber": (data["PhoneNumber"].isna() |
                        data["PhoneNumber"].str.fullmatch(r"[0-9]{10,15}", na=False)).all(),
    }
    failed = [name for name, valid in checks.items() if not valid]
    if failed:
        raise DataValidationError(f"Validácia zlyhala: {', '.join(failed)}")

validate_clean(clean_data)
print("Čisté dáta prešli opätovnou validáciou.")

Čisté dáta prešli opätovnou validáciou.

<h2 style="margin: 24px 0 16px; font-size: 20px; font-weight: 600; font-family: 'Segoe UI', Roboto, sans-serif; color: #111827; border-bottom: 2px solid #e5e7eb; padding-bottom: 6px;">💻 Úloha 13 – Uloženie výsledkov validácie</h2>
<p style="font-family: 'Segoe UI', Roboto, sans-serif; color: #1f2937; line-height: 1.65; margin: 8px 0 12px;">Na konci vytvorte samostatné výstupy pre dáta, ktoré môžu pokračovať do ďalšieho spracovania, a pre záznamy, ktoré vyžadujú kontrolu.</p>
<ul style="font-family: 'Segoe UI', Roboto, sans-serif; color: #1f2937; line-height: 1.7; margin-top: 6px;">
<li>uložte čisté dáta ako <span style="background-color: #e5e7eb; color: #111827; font-family: monospace; padding: 2px 5px; border-radius: 4px;">sales_data_clean.csv</span>,</li>
<li>uložte zamietnuté riadky ako <span style="background-color: #e5e7eb; color: #111827; font-family: monospace; padding: 2px 5px; border-radius: 4px;">sales_data_rejected.csv</span>,</li>
<li>uložte validačný report ako <span style="background-color: #e5e7eb; color: #111827; font-family: monospace; padding: 2px 5px; border-radius: 4px;">validation_report.csv</span>.</li>
</ul>
<div style="margin-top: 12px; background-color: #f9fafb; border-left: 4px solid #60a5fa; padding: 12px; border-radius: 4px;"> 💡 <strong>Pomôcka:</strong> Výsledok validácie nemusí byť iba jeden „opravený“ súbor.
V praxi je užitočné uchovať:
<ul style="font-family: 'Segoe UI', Roboto, sans-serif; color: #1f2937; line-height: 1.7; margin-top: 6px;">
<li>čisté dáta, ktoré môžu pokračovať ďalej,</li>
<li>zamietnuté záznamy na kontrolu,</li>
<li>súhrnný report s počtom chýb.</li>
</ul>
Na zápis CSV použite <span style="background-color: #e5e7eb; color: #111827; font-family: monospace; padding: 2px 5px; border-radius: 4px;">to_csv(..., index=False)</span>.
</div>

In [13]:
clean_data.to_csv(base_dir / "sales_data_clean.csv", index=False)
rejected_records.to_csv(base_dir / "sales_data_rejected.csv", index=False)
validation_report.to_csv(base_dir / "validation_report.csv", index=False)
print("Výstupné súbory boli uložené.")

Výstupné súbory boli uložené.

<h2
  style="margin: 24px 0 16px; font-size: 20px; font-weight: 600; font-family: 'Segoe UI', Roboto, sans-serif; color: #111827; border-bottom: 2px solid #e5e7eb; padding-bottom: 6px;">
  💻 Úloha 14 – Kontrola vytvorených výstupov
</h2>

<p style="font-family: 'Segoe UI', Roboto, sans-serif; color: #1f2937; line-height: 1.65; margin: 8px 0 12px;">
  Po uložení výsledkov validácie znovu načítajte vytvorené súbory a skontrolujte,
  či obsahujú očakávané údaje.
</p>

<p style="font-family: 'Segoe UI', Roboto, sans-serif; color: #1f2937; line-height: 1.65; margin: 8px 0 12px;">
  Načítajte a zobrazte prvých niekoľko riadkov súborov:
</p>

<ul style="font-family: 'Segoe UI', Roboto, sans-serif; color: #1f2937; line-height: 1.7; margin-top: 6px;">
  <li><span style="background-color: #e5e7eb; color: #111827; font-family: monospace; padding: 2px 5px; border-radius: 4px;">sales_data_clean.csv</span>,</li>
  <li><span style="background-color: #e5e7eb; color: #111827; font-family: monospace; padding: 2px 5px; border-radius: 4px;">sales_data_rejected.csv</span>,</li>
  <li><span style="background-color: #e5e7eb; color: #111827; font-family: monospace; padding: 2px 5px; border-radius: 4px;">validation_report.csv</span>.</li>
</ul>

<p style="font-family: 'Segoe UI', Roboto, sans-serif; color: #1f2937; line-height: 1.65; margin: 8px 0 12px;">
  Pri každom výstupe skontrolujte:
</p>

<ul style="font-family: 'Segoe UI', Roboto, sans-serif; color: #1f2937; line-height: 1.7; margin-top: 6px;">
  <li>počet riadkov a stĺpcov,</li>
  <li>názvy stĺpcov,</li>
  <li>dátové typy,</li>
  <li>prvých 5 riadkov.</li>
</ul>

In [ ]:
loaded_outputs = {}
for filename in ["sales_data_clean.csv", "sales_data_rejected.csv", "validation_report.csv"]:
    if filename == "sales_data_clean.csv":
        output = pd.read_csv(base_dir / filename, dtype={
            "OrderID": "string", "CustomerName": "string", "Region": "string",
            "Product": "string", "Quantity": "Int64", "SalesAmount": "Float64",
            "Discount": "Float64", "PhoneNumber": "string"},
            parse_dates=["OrderDate", "DeliveryDate"])
    else:
        output = pd.read_csv(base_dir / filename, dtype="string")
    loaded_outputs[filename] = output
    print(filename, "- počet riadkov a stĺpcov:", output.shape)
    print(output.columns.tolist())
    print(output.dtypes)
    display(output.head())
validate_clean(loaded_outputs["sales_data_clean.csv"])
if len(clean_data) + len(rejected_records) != len(df):
    raise DataValidationError("Počet výstupných riadkov nesedí so vstupom.")
print("Výstupy boli znovu načítané a skontrolované.")

sales_data_clean.csv – počet riadkov a stĺpcov: (84, 10)
['OrderID', 'CustomerName', 'Region', 'Product', 'Quantity', 'SalesAmount', 'Discount', 'OrderDate', 'DeliveryDate', 'PhoneNumber']
OrderID         string[python]
CustomerName    string[python]
Region          string[python]
Product         string[python]
Quantity                 Int64
SalesAmount            Float64
Discount               Float64
OrderDate       datetime64[ns]
DeliveryDate    datetime64[ns]
PhoneNumber     string[python]
dtype: object

,OrderID,CustomerName,Region,Product,Quantity,SalesAmount,Discount,OrderDate,DeliveryDate,PhoneNumber
0,ORD1015,Charlie Lee,West,Phone,7,840.0,20.0,2025-01-16,2025-01-19,<NA>
1,ORD1030,Alice Johnson,West,Phone,6,1805.15,15.0,2025-01-31,2025-02-01,<NA>
2,ORD1128,Bob Smith,South,Laptop,9,3083.23,5.0,2025-05-09,2025-05-11,<NA>
3,ORD1170,Lola Ade,North,Accessory,1,1380.89,10.0,2025-06-20,2025-06-22,<NA>
4,ORD1066,David King,South,Tablet,8,2089.21,25.0,2025-03-08,2025-03-18,08012345678

sales_data_rejected.csv – počet riadkov a stĺpcov: (116, 12)
['OrderID', 'CustomerName', 'Region', 'Product', 'Quantity', 'SalesAmount', 'Discount', 'OrderDate', 'DeliveryDate', 'PhoneNumber', 'rejection_reasons', 'invalid_phone']
OrderID              string[python]
CustomerName         string[python]
Region               string[python]
Product              string[python]
Quantity             string[python]
SalesAmount          string[python]
Discount             string[python]
OrderDate            string[python]
DeliveryDate         string[python]
PhoneNumber          string[python]
rejection_reasons    string[python]
invalid_phone        string[python]
dtype: object

,OrderID,CustomerName,Region,Product,Quantity,SalesAmount,Discount,OrderDate,DeliveryDate,PhoneNumber,rejection_reasons,invalid_phone
0,ORD1095,Bob Smith,South,Unknown,-1,2710.16,15,2025-04-06,2024-02-30,+2348012345678,invalid_product; invalid_quantity_range; inval...,False
1,ORD1158,Ibrahim Musa,North,phone,0,<NA>,5,2025-06-08,2025-06-21,+1-202-555-0178,missing_SalesAmount; invalid_quantity_range,False
2,ORD1115,Rita Gomez,North,Unknown,-1,3876.36,10,2025-04-26,2025-05-04,+1-202-555-0178,invalid_product; invalid_quantity_range,False
3,ORD1069,Oluwaseun Adebayo,north,Tablet,3.5,2518.94,<NA>,2025-03-11,2025-03-15,(202) 555-0189,missing_Discount; invalid_quantity_range,False
4,ORD1174,Alice Johnson,South,Unknown,9,3710.03,15,2025-06-24,2025-07-02,+1-202-555-0178,invalid_product,False

validation_report.csv – počet riadkov a stĺpcov: (17, 3)
['rule', 'error_count', 'severity']
rule           string[python]
error_count    string[python]
severity       string[python]
dtype: object

                 rule error_count  severity
0    invalid_order_id           0  critical
1  duplicate_order_id          22  critical
2      invalid_region           0  critical
3     invalid_product          31  critical
4    missing_Quantity           0  critical

Výstupy boli znovu načítané a skontrolované.

<p style="font-family: 'Segoe UI', Roboto, sans-serif; color: #1f2937; line-height: 1.65; margin: 8px 0 12px;">
Po tejto časti by ste nemali validáciu dát vnímať iba ako kontrolu chýbajúcich hodnôt alebo jednoduché odstránenie chybných riadkov.
</p>

<p style="font-family: 'Segoe UI', Roboto, sans-serif; color: #1f2937; line-height: 1.65; margin: 8px 0 12px;">
Mali by ste vedieť:
</p>

<ul style="font-family: 'Segoe UI', Roboto, sans-serif; color: #1f2937; line-height: 1.7; margin-top: 6px;">
<li>bezpečne načítať vstupný súbor a vhodne reagovať na chyby pri jeho spracovaní,</li>
<li>skontrolovať štruktúru datasetu, dátové typy a chýbajúce hodnoty,</li>
<li>overiť, či vstup obsahuje všetky očakávané stĺpce,</li>
<li>identifikovať nesprávne formáty, neplatné hodnoty a duplicity,</li>
<li>zjednotiť nekonzistentné textové a kategóriové hodnoty,</li>
<li>bezpečne konvertovať číselné a dátumové údaje,</li>
<li>kontrolovať nielen formát údajov, ale aj ich logickú správnosť,</li>
<li>vytvoriť validačné pravidlá a prehľad nájdených problémov,</li>
<li>oddeliť validné záznamy od záznamov, ktoré vyžadujú ďalšiu kontrolu,</li>
<li>opätovne overiť vyčistené dáta pred ich ďalším spracovaním alebo uložením.</li>
</ul>

<p style="font-family: 'Segoe UI', Roboto, sans-serif; color: #1f2937; line-height: 1.65; margin: 8px 0 12px;">
Pri práci s dátami nie je cieľom každú chybu automaticky opraviť alebo nahradiť nulou. Najskôr je potrebné problém identifikovať, pochopiť jeho význam a až potom rozhodnúť, či je možné hodnotu bezpečne opraviť, označiť ako neplatnú alebo celý záznam oddeliť na ďalšiu kontrolu.
</p>

<p style="font-family: 'Segoe UI', Roboto, sans-serif; color: #1f2937; line-height: 1.65; margin: 8px 0 12px;">
Takýto postup je dôležitý najmä pri automatizovanom spracovaní dát, kde sa rovnaká validácia môže opakovane vykonávať nad novými vstupnými súbormi ešte predtým, než sa dáta dostanú do ďalších častí dátovej pipeline.
</p>

<h2
  style="margin: 24px 0 16px; font-size: 20px; font-weight: 600; font-family: 'Segoe UI', Roboto, sans-serif; color: #111827; border-bottom: 2px solid #e5e7eb; padding-bottom: 6px;">
  📘 Kontrola Git repozitára po 5. týždni
</h2>

<p style="color: #1f2937; line-height: 1.65;">
  Po dokončení všetkých úloh z 5. týždňa skontrolujte, či máte vo svojom Git
  repozitári vytvorenú samostatnú vetvu
  <span
    style="background-color: #e5e7eb; color: #111827; font-family: monospace; padding: 2px 5px; border-radius: 4px;">week-05</span>
  a či sa v nej nachádzajú všetky notebooky, vstupné datasety a výstupné súbory
  vytvorené počas cvičenia.
</p>

<p style="color: #1f2937; line-height: 1.65;">
  Obsah vetvy
  <span
    style="background-color: #e5e7eb; color: #111827; font-family: monospace; padding: 2px 5px; border-radius: 4px;">week-05</span>
  by mal mať približne nasledujúcu štruktúru:
</p>

<pre
  style="background: #f9fafb; color: #111827; padding: 16px; border-radius: 8px; overflow: auto; font-size: 14px; line-height: 1.7; font-family: ui-monospace, SFMono-Regular, Menlo, monospace;">week-05
│
├── file_handling.ipynb
├── error_handling.ipynb
│
├── high_salary.csv
├── it_employees.csv
├── west_region_sales.xlsx
│
├── sales_report.parquet
├── sales_report2.parquet
├── yellow_tripdata_2024-01.parquet
│
├── sales_data_dirty.csv
├── sales_data_clean.csv
├── sales_data_rejected.csv
└── validation_report.csv</pre>

<p style="color: #1f2937; line-height: 1.65;">
  V repozitári ponechajte nielen samotné notebooky, ale aj vstupné a výstupné
  súbory, s ktorými ste počas cvičenia pracovali. Vďaka tomu bude možné neskôr
  skontrolovať jednotlivé kroky spracovania dát a nadviazať na ne v ďalších
  častiach dátovej pipeline.
</p>

<div
  style="margin-top: 12px; background-color: #fff7ed; border-left: 4px solid #f59e0b; padding: 12px; border-radius: 4px;">
  ⚠️ <strong>Kontrola GitHubu:</strong> Skontrolujte, či sa všetky uvedené súbory
  nachádzajú aj vo vzdialenom repozitári na GitHube. Ak ich vidíte iba lokálne
  vo VS Code, zmeny ešte neboli úspešne odoslané pomocou
  <strong>commit</strong> a <strong>push</strong>.
</div>